/**
 * Generate the reference pages that come from code: docs/reference/commands.md (the command registry),
 * effects.md (the built-in catalog) and errors.md (every E_/W_ code found in src/ with its fix).
 * `--check` exits 1 when a committed page is out of date.
 */
import { existsSync, readFileSync, readdirSync, statSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join, relative } from 'node:path';
import { fileURLToPath } from 'node:url';
import { MglError } from '../src/core/errors.js';
import { exampleLine, listCommands, type CommandDef } from '../src/core/commands/index.js';
import { builtinRegistry } from '../src/builtin/index.js';
import { fieldsOf, type FieldDoc } from '../src/cli/docs.js';
import type { z } from 'zod';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const REF = join(ROOT, 'docs', 'reference');
const HEADER = (what: string) => `<!-- generated by scripts/gen-docs.ts from ${what}; do not edit by hand (npm run docs) -->\n`;

const md = (s: string) => s.replace(/\|/g, '\\|');
const fieldText = (f: FieldDoc) => `\`${f.name}${f.required ? '' : '?'}\` ${md(f.type)}${f.default !== undefined ? ` = \`${JSON.stringify(f.default)}\`` : ''}${f.describe ? ` · ${md(f.describe)}` : ''}`;

export function commandsPage(): string {
  const groups = new Map<string, CommandDef[]>();
  for (const c of listCommands()) groups.set(c.group, [...(groups.get(c.group) ?? []), c]);
  const out = [HEADER('the command registry'), '# Commands', '',
    'Every change to a project is a command `{"op": ..., fields}`, run with `mgl edit <file> <op> [bare] k=v ...`, as JSON',
    '(`mgl edit <file> \'{"op": ...}\'`, `--batch f.jsonl`) or from the SDK (`p.edit({op, ...})`). Times accept frames (75),',
    '"2.5s", "1:02.5" and "00:01:02:15". `k=v` values are JSON when they parse, else strings. `mgl docs <op>` prints one entry.', '',
    `${listCommands().length} commands: ${[...groups.keys()].map((g) => `[${g}](#${g})`).join(' · ')}`, ''];
  for (const [g, cs] of groups) {
    out.push(`## ${g}`, '');
    for (const c of cs) {
      const fields = fieldsOf(c.schema);
      out.push(`### ${c.op}`, '', c.doc, '');
      out.push(`fields: ${fields.map((f) => `${fieldText(f)}${c.primary === f.name ? ' (bare word)' : ''}`).join('; ')}`, '');
      out.push('```text', exampleLine(c).replace('<file>', 'video.mgl.json'), JSON.stringify({ op: c.op, ...c.example }), '```', '');
    }
  }
  return out.join('\n');
}

export function effectsPage(): string {
  const reg = builtinRegistry();
  const params = (p?: z.ZodType) => (p && 'shape' in (p as object) ? fieldsOf(p as z.ZodObject).map(fieldText).join('; ') : '');
  const out = [HEADER('the built-in plugin registry'), '# Effects, transitions, generators, templates, styles', '',
    'The built-in catalog (every entry is a plugin-API definition in `src/builtin/`; plugins add more). `mgl docs <name>` prints one.', '',
    '## Effects', '', '`fx` on a clip is an ordered list: `mgl edit video.mgl.json fx.add shot1 type=blur radius=8`; address a parameter as',
    '`fx.blur.radius` (first of that type) or `fx.0.radius`. Numeric parameters accept keyframes. Stage `source` runs in ffmpeg while',
    'decoding (media clips only); `layer` runs in Skia on the rendered layer.', ''];
  for (const [id, e] of reg.effects) out.push(`- **${id}** (${[e.source ? 'source' : '', e.draw ? 'layer' : ''].filter(Boolean).join(' + ')}): ${md(e.describe)}${params(e.params) ? `  \n  ${params(e.params)}` : ''}`);
  out.push('', '## Transitions', '', 'A transition is the incoming clip\'s `in` (centred on the cut): `mgl edit video.mgl.json transition.set shot2 type=wipe len=0.5s`.', '');
  for (const [id, t] of reg.transitions) out.push(`- **${id}**: ${md(t.describe)}${params(t.params) ? `  \n  ${params(t.params)}` : ''}`);
  out.push('', '## Generators', '', 'Clips that draw: `{"gen": {"type": "gradient", "colors": ["#000", "#333"]}}`.', '');
  for (const [id, g] of reg.generators) out.push(`- **${id}**: ${md(g.describe)}${params(g.params) ? `  \n  ${params(g.params)}` : ''}`);
  out.push('', '## Templates', '', '`mgl edit video.mgl.json template.apply <id> at=1s params=\'{...}\'` (see templates.md).', '');
  for (const [id, t] of reg.templates) out.push(`- **${id}**: ${md(t.describe)}${params(t.params) ? `  \n  ${params(t.params)}` : ''}`);
  out.push('', '## Styles', '', 'Built-in text styles, usable as `"style": "<id>"` or as `base` of your own style.', '');
  for (const [id, s] of reg.styles) out.push(`- **${id}**: ${md(s.describe)} \`${md(JSON.stringify(s.style))}\``);
  out.push('', '## Text animations', '', '`text.animate <clip> in=<id> by=word` (char, word, line, all).', '');
  out.push(`${[...reg.textAnimations].map(([id, a]) => `**${id}** (${md(a.describe)})`).join(' · ')}`, '');
  return out.join('\n');
}

// ------------------------------------------------------------------------------------------- errors

function files(dir: string, out: string[] = []): string[] {
  for (const f of readdirSync(dir).sort()) {
    const p = join(dir, f);
    if (statSync(p).isDirectory()) files(p, out);
    else if (f.endsWith('.ts') && !f.endsWith('.test.ts')) out.push(p);
  }
  return out;
}

/** Split the top-level arguments of a call starting at `i` (just after "("). */
function callArgs(src: string, i: number, max = 4): string[] {
  const args: string[] = [];
  let depth = 0, start = i;
  for (; i < src.length && args.length < max; i++) {
    const ch = src[i]!;
    if (ch === '"' || ch === "'" || ch === '`') { i = skipString(src, i); continue; }
    if ('([{'.includes(ch)) depth++;
    else if (')]}'.includes(ch)) { if (depth === 0) { args.push(src.slice(start, i)); break; } depth--; }
    else if (ch === ',' && depth === 0) { args.push(src.slice(start, i)); start = i + 1; }
  }
  return args.map((a) => a.trim());
}

function skipString(src: string, i: number): number {
  const q = src[i]!;
  for (i++; i < src.length; i++) {
    if (src[i] === '\\') { i++; continue; }
    if (q === '`' && src[i] === '$' && src[i + 1] === '{') {
      let depth = 1;
      for (i += 2; i < src.length && depth; i++) {
        if (src[i] === '{') depth++;
        else if (src[i] === '}') depth--;
        else if (src[i] === '`' || src[i] === '"' || src[i] === "'") i = skipString(src, i);
      }
      i--;
      continue;
    }
    if (src[i] === q) return i;
  }
  return i;
}

/** Readable text of a string expression: literals kept, ${...} and other expressions shown as "…". */
function textOf(expr: string): string {
  const parts: string[] = [];
  let depth = 0;
  for (let i = 0; i < expr.length; i++) {
    const ch = expr[i]!;
    if ('([{'.includes(ch)) depth++;
    else if (')]}'.includes(ch)) depth--;
    else if (ch === '/' && depth > 0) { const end = expr.indexOf('/', i + 2); if (end > 0 && /[(,]\s*$/.test(expr.slice(0, i))) { i = end; continue; } }
    if ((ch === '"' || ch === "'" || ch === '`') && depth > 0) { i = skipString(expr, i); continue; } // arguments of a call: not text
    if (ch === '"' || ch === "'" || ch === '`') {
      const end = skipString(expr, i);
      let body = expr.slice(i + 1, end);
      if (ch === '`') body = body.replace(/\$\{(?:[^{}]|\{[^{}]*\})*\}/g, '…');
      const after = expr.slice(end + 1).trimStart();
      const isOperand = /(===?|!==?)\s*$/.test(expr.slice(0, i)) || after.startsWith('?') || /^(===?|!==?)/.test(after);
      i = end;
      if (isOperand) continue; // a comparison inside a condition, not text
      parts.push(body.replace(/\\(["'`\\])/g, '$1').replace(/\\n/g, ' '));
      if (/^\+\s*[^\s'"`]/.test(after)) parts.push('…'); // 'text ' + expression
      if (after.startsWith(':')) break; // first branch of a ternary
    }
  }
  return (parts.join('') || '…').replace(/…(\s*…)+/g, '…').replace(/\s+/g, ' ').trim();
}

export interface ErrorDoc { code: string; exit: 1 | 2 | 0; message: string; fix: string; where: string[] }

export function scanErrors(): ErrorDoc[] {
  const found = new Map<string, ErrorDoc>();
  for (const f of files(join(ROOT, 'src'))) {
    const src = readFileSync(f, 'utf8');
    const rel = relative(ROOT, f);
    const re = /'((?:E|W)_[A-Z0-9_]+)'/g;
    for (let m; (m = re.exec(src));) {
      const code = m[1]!;
      let message = '', fix = '';
      const before = src.slice(Math.max(0, m.index - 80), m.index);
      const call = /(?:\bfail|\berr|\bwarn|\bissue|\bproblem|\breport)\(\s*(?:(?:\[[^\]]*\]|[\w.]+)\s*,\s*)?$/.exec(before);
      if (call) {
        const args = callArgs(src, m.index + m[0].length + 1);
        if (args.length >= 2) { message = textOf(args[0]!); fix = textOf(args[1]!); }
      } else if (/code:\s*$/.test(before)) {
        const obj = src.slice(m.index, m.index + 1500);
        const mm = /message:\s*/.exec(obj), fm = /fix:\s*/.exec(obj);
        if (mm) message = textOf(callArgs(obj, mm.index + mm[0].length, 1)[0] ?? '');
        if (fm) fix = textOf(callArgs(obj, fm.index + fm[0].length, 1)[0] ?? '');
      } else continue;
      const prev = found.get(code);
      if (prev) {
        if (!prev.where.includes(rel)) prev.where.push(rel);
        if ((!prev.fix || prev.fix === '…') && fix) { prev.fix = fix; prev.message = message; }
        continue;
      }
      const exit = code.startsWith('W_') ? 0 : new MglError({ code, message: '', fix: '' }).exitCode;
      found.set(code, { code, exit, message, fix, where: [rel] });
    }
  }
  return [...found.values()].sort((a, b) => a.code.localeCompare(b.code));
}

export function errorsPage(): string {
  const errs = scanErrors();
  const out = [HEADER('the error codes in src/'), '# Errors', '',
    'Every failure is `{code, message, fix, line?}`: a stable code, what is wrong, and the fix. Exit 1 = the input is wrong',
    '(file, command, arguments, media); exit 2 = the environment is wrong (ffmpeg, disk, network). `W_` codes are warnings:',
    'they are printed but never fail a command. With `--json` the error is `{"ok": false, "error": {...}}`. An unexpected',
    'exception is `E_INTERNAL` (exit 1). Below: each code with one example message and fix (`…` stands for names and numbers).', '',
    '| code | exit | example | fix |', '|---|---|---|---|',
    '| `E_INTERNAL` | 1 | unexpected error: … | report this; run with --debug for the stack. |',
    '| `E_USAGE` | 1 | a verb or its arguments are wrong | the usage line printed with the error (mgl help) |'];
  for (const e of errs) {
    if (e.code === 'E_INTERNAL' || e.code === 'E_USAGE') continue;
    out.push(`| \`${e.code}\` | ${e.exit || 'warning'} | ${md(e.message || '…')} | ${md(e.fix || '…')} |`);
  }
  out.push('');
  return out.join('\n');
}

export const PAGES: Record<string, () => string> = { 'commands.md': commandsPage, 'effects.md': effectsPage, 'errors.md': errorsPage };

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  const check = process.argv.includes('--check');
  const stale: string[] = [];
  mkdirSync(REF, { recursive: true });
  for (const [name, gen] of Object.entries(PAGES)) {
    const file = join(REF, name);
    const text = gen();
    if (check) { if (!existsSync(file) || readFileSync(file, 'utf8') !== text) stale.push(name); }
    else { writeFileSync(file, text); console.log(`wrote docs/reference/${name}`); }
  }
  if (check) {
    if (stale.length) { console.error(`out of date: ${stale.join(', ')}. fix: npm run docs`); process.exit(1); }
    console.log('generated docs are up to date');
  }
}
